name: recommend_movie
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # 기본 아이콘 패키지
  cupertino_icons: ^1.0.8

  http: ^1.2.0
  flutter_card_swiper: ^7.0.0
  google_sign_in: ^6.2.1
  kakao_flutter_sdk: ^1.9.0
  url_launcher: ^6.3.0
  external_app_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true